name: Build and Deploy Docker to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: SSH

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t apd:latest .

    - name: Save Docker image
      run: docker save apd:latest -o apd.zip

    - name: Copy image to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        source: apd.zip
        target: /home/dqrk/apd.zip

    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script: |
          set -e

          docker stop apd-container || true
          docker rm apd-container || true

          docker load -i /home/dqrk/apd.zip

          docker run -d \
            -p 80:80 \
            --name apd-container \
            --restart unless-stopped \
            apd:latest

          rm -fr /home/dqrk/apd.zip
          docker image prune -f

    - name: Update GitHub repo website
      run: |
        curl -X PATCH https://api.github.com/repos/${{ github.repository }} \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{"homepage":"http://'${{ secrets.HOST }}':80"}'