name: Build and Deploy Docker to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t apd:latest .

    - name: Save Docker image
      run: docker save apd:latest -o apd.tar

    - name: Copy image to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        source: "apd.tar"
        target: "~/"

    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop apd-container || true
          docker rm apd-container || true
          docker load -i ~/apd.tar
          docker run -d \
            -p 80:80 \
            --name apd-container \
            --restart unless-stopped \
            apd:latest
          docker image prune -f
          rm ~/apd.tar

    - name: Update GitHub repo website
      run: |
        curl -X PATCH https://api.github.com/repos/${{ github.repository }} \
          -H "Authorization: Bearer ${{ secrets.GITHUBTOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{"homepage":"http://${{ secrets.HOST }}:80"}'